export enum Actions {
  START_LOADING = "START_LOADING",
  FINISH_LOADING = "FINISH_LOADING",
  SAVE_SEARCH_DATA = "SAVE_SEARCH_DATA",
  SAVE_COUNTER_DATA = "SAVE_COUNTER_DATA",
  SAVE_TOP_DEBTOR_DATA = "SAVE_TOP_DEBTOR_DATA",
  SET_ACTIVE_ITEM = "SET_ACTIVE_ITEM",
  SET_ERROR = "SET_ERROR"
}
